[gcp_service_account]
type = "service_account"
project_id = "controle-de-tarefa"
private_key_id = "db9e3b5c01c7666b0891208e8b638ce7a152149a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChtdHlsiQBIvou
yh8bdiIenultueTx/yJPR6QeVCIWtmV5/XIobfem70nXjxsdpGoUfR5vmRAZsoCX
Ne6J3qkFdJOBa7kLThAijbLiTRaTe8U7j//C/21/faMTuljghE0z4lf8Zmt9ZAsY
DqV3B/zaefwxOGz4cZK6TKrVgC9PVoeQ4YJ6yO4WmFMwrlfI/0Krs7/NQ6YkLG9N
l6teHziJIqFrzrMVoKdmlAMJsOIPKmqqmI7HlX/kTfCe2edc8GlVXUa+dBsaBegu
PxeHEjJPqIsckh68bG6b5ZE70iHNMpFgpprPHrDJpU0xAuTkiQSDL/Z9e8CLwI/p
FcxLnq7RAgMBAAECggEACMCkZjggnmvMD8PtMBl875xZSmZBNTSXy6O3MdRgQ0tx
raB2pn02kMirKKl8ZbvUPrH7oj2uHeidRidAocy1PZrZhavqHZRcPN/fhUPNNi6r
oQrXudsFDF1P+iLgFEgvkjXXiPfq1yQW56FEpRnVE+bTVr9U7T40cLSdRdCvftiR
l7N0xdE7m+79tUzE30sJ2I0nNpMJ0Jqi9u0TTRnEDjjNe5iHlOyM3Su0tjyXD+Xk
546mrA41PN7wGiu6UJ7+AA6MN+xMPBzQ0B5nhKupbVp4qn34LdsneUktRSXyIF+l
4IgL/wKsYSoJH2FIojZQuchCTLz1U0gFYDVqFF3OkwKBgQDMDSxf0HYCzhFNcjCz
Au3P9n1OTOHwFXOeJakZgIrBUgGaUghBsR5RYBAViBGbDKE/vV4Ce86ltazIJIMy
2fKxMo9Cz18Sr6ixgxCtZE593APdsZVqq9lkn/cHoVuTzlhOAHuSsFnPzjuzi8P5
21Gl5pcDq8HEjFD64k474y8dTwKBgQDK4Rq6n8lhPuKuNGHxIBhRep9cH2cbnWf1
EXXDr7kRnM2YnYVnmtgEeBgjTSgaSgw1Ao0O5bNYWqoubJEB+Sv71ADdD2/0vle1
vb/dKGSNqLtZeXi3NGgrjDB2BZKANkWGtajGP6eJm41sjqOheIGsYVKc1zFciEUQ
AAXQcFWp3wKBgHEGNvcXk9Z36BOa1ajCTZGsubm+UkPWzgTiXWkXz0PHtcWR/KrO
fbmbWS1kAkR82XBh5wm/JDabjAoMV3O6T3ihRcM+9C14iRtSOtGgRu3mCWop7FZ6
u97F0GI0mXIkkLsb/1bAQe8eD+mi2Dm0puQa9rj80UaaZlyhL65yZ213AoGBAIeH
ANgSzfBMlhlRnOv7SMOFatebksF70WqBE256AOOnICEHeYrQgeXaZCWQ8W0+chEn
dxuwjrJDPtRsaiIrVhqQcVM7cMrKLMWX0Ifo5+NKCH2pC982/y+4Itd0uX00xBVN
XUWyWDUw2LTgRKclXVrOWOW1S6BI1/nsSfYIVPF5AoGAM0j3U5UX2gxZLpk3tCan
vmwDEv4dMtD1i8bCJ9RyTY57N6mgDP81ePlmkhk6CGWDjmk9GLb4nky7My/Hm/0x
Ke7Mwyvf1h6EN2LiH3heKehVIA/Cz/ZjLgkBzm5+oArkOJhWAMIk6uNUleGsMQD2
PiCJG9D3Oh4U9ub/fETcb4c=
-----END PRIVATE KEY-----
"""
client_email = "controle-de-tempo@controle-de-tarefa.iam.gserviceaccount.com"
client_id = "100182775579056514170"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/controle-de-tempo%40controle-de-tarefa.iam.gserviceaccount.com"
universe_domain = "googleapis.com"